spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 50MB
      max-file-size: 20MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tms_database
    username: kripanda
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 5000 # in msecs

springdoc:
  swagger-ui:
    path: /docs.html
  api-docs:
    path: /api/docs.yaml

jwt:
  secret: '7AA1FDEA450B39D38A2351AFEB91A1CC5C7DC48FFD8E0ED22361092291380B8E'
  expiration: '10m'